"""Initial Migration

Revision ID: 1d5207d4fd6d
Revises: 
Create Date: 2025-10-24 22:24:35.706889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d5207d4fd6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_data',
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('capital', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=True),
    sa.Column('exchange_rate', sa.Float(), nullable=True),
    sa.Column('estimated_gdp', sa.Float(), nullable=True),
    sa.Column('flag_url', sa.String(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('country_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_data')
    # ### end Alembic commands ###
